import Head from "next/head";
import Footer from "../components/Footer/Footer";
import NavBar from "../components/Navbar/NavBar";
import HomePostsDisplay from "../components/posts/HomePostsDisplay";
import { getAllPosts } from "../services/api/post";
import {} from "../i18n/consts";
import { headers } from "next/headers";

// On veut que chaque requete axios ajoute ce header
// Voir si on peut mettre ça dans un autre fichier ?
import axios from "axios";

axios.interceptors.request.use(
  function (config) {
    // Do something before request is sent
    // TODO Mettre un vrai header quand le back filtrera les requetes auth
    console.log('HY',process.env);
    console.log("middleware axios log 2",process.env.NEXT_PUBLIC_PASSPHRASE);
    config.headers.Authorization = process.env.NEXT_PUBLIC_PASSPHRASE;
    return config;
  },
  function (error) {
    // Do something with request error
    return Promise.reject(error);
  }
);



export default async function Page() {
  const headersList = headers();
  const acceptLanguageHeader = headersList.get("accept-language");
  let localeBrowser = "en-US";

  if (acceptLanguageHeader !== undefined) {
    const allLanguages = acceptLanguageHeader.split(";");
    const mainLanguageLocaleAndLanguage = allLanguages[0];
    const [locale, language] = mainLanguageLocaleAndLanguage.split(",");
    localeBrowser = locale;
  }

  const posts = await getAllPosts(localeBrowser);

  return (
    <>
      <div className="container">
        <Head>
          <title>Le blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />

        <main className="main belowNavbar">
          <HomePostsDisplay posts={posts} />
        </main>
      </div>
      <Footer />
    </>
  );
}
