import Head from "next/head";
import NavBar from "../components/Navbar/NavBar";
import PostPeek from "../components/posts/PostPeek";
import { getAllPosts } from "../services/api/post";
import styles from "../styles/Home.module.css";

export async function getServerSideProps({ req }) {
  const resp = await getAllPosts();

  return { props: { pageData: resp } };
}

export default function Home({ pageData }) {
  return (
    <div className="container">
      <Head>
        <title>Le blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className="main belowNavbar">
        <h1 className="title">Le blog</h1>
        {pageData.map((post, index) => (
          <PostPeek post={post} key={index} />
        ))}
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
