import Head from "next/head";
import Footer from "../components/Footer/Footer";
import NavBar from "../components/Navbar/NavBar";
import HomePostsDisplay from "../components/posts/HomePostsDisplay";
import PostPeek from "../components/posts/PostPeek";
import { getAllPosts } from "../services/api/post";
import styles from "../styles/Home.module.css";
import { localeToLangDictionnary } from "../i18n/allLang";
import { useContext, useEffect, useState } from "react";
import appCurrentLangContext from "../contexts/appCurrentLang";
import {} from "../i18n/consts";

export async function getServerSideProps({ req }) {
  const headersAcceptLanguages = req?.headers?.["accept-language"];

  let localeBrowser = "en-US";

  if (headersAcceptLanguages !== undefined) {
    const allLanguages = headersAcceptLanguages.split(";");
    const mainLanguageLocaleAndLanguage = allLanguages[0];
    const [locale, language] = mainLanguageLocaleAndLanguage.split(",");
    localeBrowser = locale;
  }

  const resp = await getAllPosts(localeBrowser);

  return { props: { posts: resp, userLocaleFromReqHeaders: localeBrowser } };
}

export default function Home({ posts, userLocaleFromReqHeaders }) {
  // useEffect, recharger les posts dans la bonne langue si le contexte de langue a changé

  const { appCurrentLang } = useContext(appCurrentLangContext);
  const [postsDisplayed, setPostsDisplayed] = useState(posts);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const currentLangPosts = postsDisplayed?.[0]?.language;
    if (currentLangPosts && currentLangPosts !== appCurrentLang.locale) {
      console.log("Getting posts in nex lang !");
      setIsLoading(true);
      getAllPosts(appCurrentLang.locale).then((posts) => {
        setPostsDisplayed(posts);
        setIsLoading(false);
      });
    }
  }, [appCurrentLang.locale]);

  return (
    <>
      <div className="container">
        <Head>
          <title>Le blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />

        <main className="main belowNavbar">
          <HomePostsDisplay posts={postsDisplayed} />
        </main>
      </div>
      <Footer />
    </>
  );
}
